# Generated by Django 5.2.11 on 2026-02-27 19:33

import contacts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(db_index=True, max_length=80)),
                ('phone', models.CharField(help_text='Digits/spaces/hyphens allowed, optional leading +', max_length=32, unique=True, validators=[contacts.models.validate_phone])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='contacts.contactstatus')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name'], name='contacts_co_last_na_12cfae_idx'), models.Index(fields=['created_at'], name='contacts_co_created_71b3b6_idx')],
            },
        ),
    ]
